### ISSUE TITLE
Meet-Up Times!

### ISSUE THREAD

**Issue by CodyKarch** [RJP43/CitySlaveGirls-ChicagoDailyTimes1888#11]
Hey, just so that we get some constant work done for the Nelson project, me and @KariWomack are going to meet in the classroom Wednesday (11/4/15) and Friday (11/6/15) at 6pm to 8pm this week!!! If anybody would like to join us to accomplish stuff, @rCarls @spadafour @RJP43 , we will be there! :D

**Comment by RJP43** [comment]
Nice!!! Thanks @CodyKarch  and @KariWomack  for meeting with me yesterday I felt like we really got a lot done in coming to an understanding of what needs to be done for the project.    I won't make it this Friday due to me being at the conference; however, I will see you both on Wednesday! 

@KariWomack I saw your transcription upload... well done!!
