### ISSUE TITLE
12/17 Project work

### ISSUE THREAD

**Issue by spadafour** [RJP43/CitySlaveGirls-ChicagoDailyTimes1888#24]
@RJP43 @CodyKarch @KariWomack 
Hey guys! Just letting you know that I'm up at Press Room 122 in Village Hall working. I know you guys won't be ready to work until later, but just wanted to give you an update.

**Comment by spadafour** [comment]
@RJP43 Are you out of your final yet?

**Comment by RJP43** [comment]
@spadafour @CodyKarch @KariWomack can everyone please **SYNC** the latest version of the articles you are working on. I need all of the articles with the correct basic structural elements, `<unclear>`, `<said>`, `<p>`, and `<rs type="interruption">` elements in place so that I can turn them into HTML pages. 

@KariWomack were you able to finish article 7-31 getting the `<said>` tags in place? 
@CodyKarch where does article 8-08 stand?
 Please let us know in this issue where you both are at with those articles so we can know what more needs done. 

Also @KariWomack as you start the javascript for the class toggling please let me know what you are calling the file so I can write the line in to the head of the articles in the XSLT before I transform them. Maybe call it something like speechToggle? I don;t know up to you just let me know. Get as far as you can with this and we can clean it up tomorrow. 

@spadafour I am getting ready to review what you completed today here shortly and will write more in another comment with feedback on that. 

What time are we meeting tomorrow and where? I believe we had said 9-3 in the press room, but let's just verify that here.

**Comment by RJP43** [comment]
Okay, well I am here on campus. It takes a lot of effort for me to get to campus since I can't drive and I don't see anyone else here. I am not going to let my ride leave until I here back from someone saying they are coming because if he leaves and goes home it will be a hour drive home, a hour drive back to get me, and another hour drive back home. I'm not going to ask my ride to do that for no reason if no one is showing up. PLEASE TEXT ME OR MESSAGE ON HERE IN THE NEXT 15 MINUTES IF YOU ARE COMING TO CAMPUS! Otherwise I am leaving and will work on things virtually. My number is 412 417 4021
