### ISSUE TITLE
Meeting Times

### ISSUE THREAD

**Issue by KariWomack** [RJP43/CitySlaveGirls-ChicagoDailyTimes1888#3]
I am available MWF from 11:30-1, and after 3:00, or T TH, until 2:30, from 4-5:15, or after 7.

**Comment by CodyKarch** [comment]
Going off of Kari, I am available MWF from 3 to 4 or TuTh from 10 to 11:30.

**Comment by RJP43** [comment]
I typically have instructor meeting Fridays from 3-?, but that is flexible as long as I give early notice. I work right after my classes on Monday - Wednesday and typically don't come to campus at all on Tuesdays or Thursdays; however, I wouldn't mind coming to campus for us to meet. 

@rCarls @spadafour does Thursday or Friday work better for each of you?

**Comment by RJP43** [comment]
We decided to just meet Friday right after class. Therefore, I am closing this issue since we no longer need to figure out a meeting time. I expect that much of the collaboration will be via email and Github and whatever can't be relayed those two ways can be discussed right after class on any given class day.
